version: '2'
services:
  python-dev-nvidia:
    image: nmirinagoyansaito/python-dev-nvidia
    build:
      context: python-dev-nvidia
      args:
        - USER
    stdin_open: true
    tty: true
    volumes:
       - ./workdir/python-dev-nvidia:/home/${USER}/workdir
  tensorflow-nv:
    image: nmirinagoyansaito/tensorflow-nv
    build:
      context: tensorflow-nv
    ports:
     - "8888"
    stdin_open: true
    tty: true
    volumes:
       - ./workdir/tensorflow-nv:/home/${USER}/workdir
